name: universe_example
description: A complete example showing many use cases of using Universe package in Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  universe:
    path: ../
  
  flutter_svg: ^0.22.0
  video_player: ^2.1.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/marker.png
    - assets/marker.svg
    - assets/locator.svg
    - assets/startrek.png
    - assets/uqm_map_full.png
    - assets/berlin.mbtiles
    - assets/map/anholt_osmbright/12/2177/
    - assets/map/anholt_osmbright/12/2178/
    - assets/map/anholt_osmbright/12/2179/
    - assets/map/anholt_osmbright/12/2180/
    - assets/map/anholt_osmbright/12/2181/
    - assets/map/anholt_osmbright/13/4354/
    - assets/map/anholt_osmbright/13/4355/
    - assets/map/anholt_osmbright/13/4356/
    - assets/map/anholt_osmbright/13/4357/
    - assets/map/anholt_osmbright/13/4358/
    - assets/map/anholt_osmbright/13/4359/
    - assets/map/anholt_osmbright/13/4360/
    - assets/map/anholt_osmbright/13/4361/
    - assets/map/anholt_osmbright/13/4362/
    - assets/map/anholt_osmbright/13/4363/
    - assets/map/anholt_osmbright/14/8709/
    - assets/map/anholt_osmbright/14/8710/
    - assets/map/anholt_osmbright/14/8711/
    - assets/map/anholt_osmbright/14/8712/
    - assets/map/anholt_osmbright/14/8713/
    - assets/map/anholt_osmbright/14/8714/
    - assets/map/anholt_osmbright/14/8715/
    - assets/map/anholt_osmbright/14/8716/
    - assets/map/anholt_osmbright/14/8717/
    - assets/map/anholt_osmbright/14/8718/
    - assets/map/anholt_osmbright/14/8719/
    - assets/map/anholt_osmbright/14/8720/
    - assets/map/anholt_osmbright/14/8721/
    - assets/map/anholt_osmbright/14/8722/
    - assets/map/anholt_osmbright/14/8723/
    - assets/map/anholt_osmbright/14/8724/
    - assets/map/anholt_osmbright/14/8725/
    - assets/map/anholt_osmbright/14/8726/
    - assets/map/anholt_osmbright/14/8727/