name: universe
description: The easy & flexible way to use interactive maps in Flutter. Inspired by Leaflet.js.
version: 0.0.4-nullsafety
# author: Salman S
homepage: https://github.com/salkuadrat/universe
repository: https://github.com/salkuadrat/universe
module:
  androidX: true

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.17.0
  tuple: ^2.0.0
  logging: ^1.0.1
  vector_math: ^2.1.0
  proj4dart: ^2.0.0
  flutter_svg: ^0.22.0
  html_unescape: ^2.0.0
  cached_network_image: ^3.1.0-alpha.1
  curved_animation_controller: ^1.1.0
  location: ^4.1.1
  video_player: ^2.1.1
  provider: ^5.0.0
  flutter_geocoder: ^0.2.2-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/universe/assets/marker.svg
    - packages/universe/assets/marker2.svg
    - packages/universe/assets/compass.svg
    