name: universe
description: The easy & flexible way to use interactive maps in Flutter. Inspired by Leaflet.js.
version: 1.1.3
# author: Salman S
homepage: https://salkuadrat.github.io/universe
repository: https://github.com/salkuadrat/universe

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  tuple: ^2.0.0
  logging: ^1.0.2
  vector_math: ^2.1.2
  proj4dart: ^2.0.0
  flutter_svg: ^1.1.0
  html_unescape: ^2.0.0
  provider: ^6.0.3
  location: ^4.4.0
  geocode: ^1.0.1
  flutter_image: ^4.1.3
  video_player: ^2.4.4
  extended_image: ^7.0.0-dev.1
  cached_network_image: ^3.2.1
  curved_animation_controller: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/marker.svg
    - assets/compass.svg
  plugin:
    platforms:
      android:
        package: com.salkuadrat.universe
        pluginClass: UniversePlugin
      ios:
        pluginClass: UniversePlugin
